########################
# サービス区分のタグ
########################
# prd-aのコードl変更
'service: prd-a':
  - changed-files:
      - any-glob-to-any-file: 'prd-a/**'
'service: prd-b':
  - changed-files:
      - any-glob-to-any-file: 'prd-b/**'

########################
# プルリクエストの性質区分
########################
# ブランチ名から機能追加・修正系と判定されるとき
enhancement:
  - head-branch: ['^feat', '^feature']

# ブランチ名からバグ修正系と判定されるとき
bug:
  - head-branch: ['^fix', '^bug', '^hotfix']

# developブランチからのPRはリリースノートから除外
skip-changelog:
  - head-branch: ['develop']
