name-template: 'prd-b/v$RESOLVED_VERSION'
tag-template: 'prd-b/v$RESOLVED_VERSION'
tag-prefix: 'prd-b/'
include-labels:
  - 'service: prd-b'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
filter-by-label: true

categories:
  - title: '### ✨ 新機能 & 改善'
    label: 'enhancement'
  - title: '### 🐛 バグ修正'
    label: 'bug'
  - title: '### 📚 ドキュメント'
    label: 'documentation'
  - title: '### ♻️ その他の変更'
    label: 'other'

template: |
  ## Prd Bの変更点

  $CHANGES
