name-template: 'prd-a/v$RESOLVED_VERSION'
tag-template: 'prd-a/v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
filter-by-label: true

# hub-backendのラベルが付いたPRのみを対象
include-labels:
  - 'service: prd-a'

categories:
  - title: '### ✨ 新機能 & 改善'
    label: 'enhancement'
  - title: '### 🐛 バグ修正'
    label: 'bug'
  - title: '### 📚 ドキュメント'
    label: 'documentation'
  - title: '### ♻️ その他の変更'
    label: 'other'

template: |
  ## Prd Aの変更点

  $CHANGES
