# 日付ベースのバージョンをワークフロー側で計算するため、
# テンプレートは$RESOLVED_VERSIONをそのまま使用
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
tag-prefix: 'prd-a/'
include-labels:
  - 'service: prd-a'
exclude-labels:
  - 'skip-changelog'  # リリースノートから除外

# 日付ベースバージョニングのため、version-resolverは不要
# バージョンはワークフロー側で計算して明示的に指定

categories:
  - title: '✨ 新機能 & 改善'
    label: 'enhancement'
  - title: '🐛 バグ修正'
    label: 'bug'
  - title: '📚 ドキュメント'
    label: 'documentation'
  - title: '♻️ その他の変更'
    label: 'other'

template: |
  ## 変更点

  $CHANGES
