filter-by-label: true

tag-prefix: 'prd-b-'

# hub-backendのラベルが付いたPRのみを対象
include-labels:
  - 'service: prd-b'

categories:
  - title: '### ✨ 新機能 & 改善'
    label: 'enhancement'
  - title: '### 🐛 バグ修正'
    label: 'bug'
  - title: '### 📚 ドキュメント'
    label: 'documentation'
  - title: '### ♻️ その他の変更'
    label: 'other'

template: |
  ## Prd Bの変更点

  $CHANGES
