version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
filter-by-label: true

categories:
  - title: '### ✨ 新機能 & 改善'
    label: 'enhancement'
  - title: '### 🐛 バグ修正'
    label: 'bug'
  - title: '### 📚 ドキュメント'
    label: 'documentation'
  - title: '### ♻️ その他の変更'
    label: 'other'

template: |
  ## 変更点

  $CHANGES
