name: Draft prd-b Release

on:
  push:
    tags:
      - 'prd-b-v*'

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Draft Release
        uses: ./.github/actions/draft-release
        with:
          service: 'prd-b'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
