name: Empty matrix job test

on:
  pull_request:
    branches:
      - main

jobs:
  not-empty:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version: ["v1", "v2", "v3"]
        exclude:
          - version: "v1"
          - version: "v2"
    steps:
      - uses: actions/checkout@v3
      - name: show version
        run: |
          echo "version: ${{ matrix.version }}"

  empty-by-exclude:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version: ["v1", "v2", "v3"]
        exclude:
          - version: "v1"
          - version: "v2"
          - version: "v3"
    steps:
      - uses: actions/checkout@v3
      - name: show version
        run: |
          echo "version: ${{ matrix.version }}"

  # empty:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: [] # this cause schema error: "Array has too few items. Expected 1 or more."
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: show version
  #       run: |
  #         echo "version: ${{ matrix.version }}"
