name: Empty matrix job test

on:
  pull_request:
    branches:
      - main

jobs:
  get_target_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_target_versions.outputs.versions }}
    steps:
      - name: Find terraform resource dirs
        id: get_target_versions
        run: |
          echo 'versions=["v1", "v2", "v3"]' >> $GITHUB_OUTPUT

  not_empty:
    runs-on: ubuntu-latest
    needs: get_target_versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.get_target_versions.outputs.versions) }}
        exclude:
          - version: "v1"
          - version: "v2"
    steps:
      - name: show version
        run: |
          echo "version: ${{ matrix.version }}"

  empty_by_exclude:
    runs-on: ubuntu-latest
    needs: get_target_versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.get_target_versions.outputs.versions) }}
        exclude:
          - version: "v1"
          - version: "v2"
          - version: "v3"
    steps:
      - name: show version
        run: |
          echo "version: ${{ matrix.version }}"

  # empty:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       version: [] # this cause schema error: "Array has too few items. Expected 1 or more."
  #   steps:
  #     - name: show version
  #       run: |
  #         echo "version: ${{ matrix.version }}"
