name: tmp tag checkout
run-name: tmp tag checkout
on:
  workflow_dispatch:
  push:
    tags:
      - 'tmp/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail if tagged commit is not in main branch
        run: |
          BRANCHES=$(git branch --contains | sed 's/^\* //')
          set -- $BRANCHES
          printf "Branches: $BRANCHES\n"
          for BRANCH in $BRANCHES ; do
            if [[ "$BRANCH" == "main" ]]; then
              exit 0
            fi
          done
          exit 1
