name: Update Release Drafts

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update_drafts:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Check pull request labels
        id: check_labels
        run: |
          labels=$(echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -r '.[]')
          echo "Labels: $labels"

          if echo "$labels" | grep -q "service: prd-a"; then
            echo "has_prd_a=true" >> $GITHUB_OUTPUT
          fi

          if echo "$labels" | grep -q "service: prd-b"; then
            echo "has_prd_b=true" >> $GITHUB_OUTPUT
          fi

      - name: Update prd-a Draft Release
        if: steps.check_labels.outputs.has_prd_a == 'true'
        uses: ./.github/actions/update-service-draft
        with:
          service: prd-a
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update prd-b Draft Release
        if: steps.check_labels.outputs.has_prd_b == 'true'
        uses: ./.github/actions/update-service-draft
        with:
          service: prd-b
          github_token: ${{ secrets.GITHUB_TOKEN }}
