name: Update Release Drafts

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update_drafts:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Update prd-a Draft Release
        uses: ./.github/actions/update-service-draft
        with:
          service: prd-a
          pr_labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update prd-b Draft Release
        uses: ./.github/actions/update-service-draft
        with:
          service: prd-b
          pr_labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
